/*
  Warnings:

  - You are about to drop the column `deletedAt` on the `customers` table. All the data in the column will be lost.
  - You are about to drop the column `deletedAt` on the `employees` table. All the data in the column will be lost.
  - You are about to drop the column `deletedAt` on the `factories` table. All the data in the column will be lost.
  - You are about to drop the column `deletedAt` on the `machines` table. All the data in the column will be lost.
  - You are about to drop the column `deletedAt` on the `materials` table. All the data in the column will be lost.
  - You are about to drop the column `deletedAt` on the `products` table. All the data in the column will be lost.
  - You are about to drop the column `deletedAt` on the `sales_orders` table. All the data in the column will be lost.
  - You are about to drop the column `deletedAt` on the `suppliers` table. All the data in the column will be lost.
  - You are about to drop the column `deletedAt` on the `warehouses` table. All the data in the column will be lost.

*/
-- DropForeignKey
ALTER TABLE "cost_sheets" DROP CONSTRAINT "cost_sheets_productionBatchId_fkey";

-- DropForeignKey
ALTER TABLE "material_consumptions" DROP CONSTRAINT "material_consumptions_productionBatchId_fkey";

-- DropForeignKey
ALTER TABLE "quality_inspections" DROP CONSTRAINT "quality_inspections_productionBatchId_fkey";

-- DropForeignKey
ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_materialId_fkey";

-- DropForeignKey
ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_productId_fkey";

-- AlterTable
ALTER TABLE "customers" DROP COLUMN "deletedAt";

-- AlterTable
ALTER TABLE "employees" DROP COLUMN "deletedAt";

-- AlterTable
ALTER TABLE "factories" DROP COLUMN "deletedAt";

-- AlterTable
ALTER TABLE "machines" DROP COLUMN "deletedAt";

-- AlterTable
ALTER TABLE "materials" DROP COLUMN "deletedAt";

-- AlterTable
ALTER TABLE "production_batches" ADD COLUMN     "deletedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "products" DROP COLUMN "deletedAt";

-- AlterTable
ALTER TABLE "sales_orders" DROP COLUMN "deletedAt";

-- AlterTable
ALTER TABLE "suppliers" DROP COLUMN "deletedAt";

-- AlterTable
ALTER TABLE "warehouses" DROP COLUMN "deletedAt";

-- AddForeignKey
ALTER TABLE "material_consumptions" ADD CONSTRAINT "material_consumptions_productionBatchId_fkey" FOREIGN KEY ("productionBatchId") REFERENCES "production_batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_materialId_fkey" FOREIGN KEY ("materialId") REFERENCES "materials"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "quality_inspections" ADD CONSTRAINT "quality_inspections_productionBatchId_fkey" FOREIGN KEY ("productionBatchId") REFERENCES "production_batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cost_sheets" ADD CONSTRAINT "cost_sheets_productionBatchId_fkey" FOREIGN KEY ("productionBatchId") REFERENCES "production_batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- P0 remediation (DB-002), hand-authored (not generated by `prisma migrate dev`'s schema
-- diff): PostgreSQL unique constraints treat NULL as distinct from NULL, so the existing
-- @@unique([warehouseId, locationId, productId, materialId, batchNumber]) on "stock" does
-- NOT prevent two concurrent first-writes for the same (warehouse, no-location,
-- product-or-material, no-batch) identity from both succeeding as two separate rows --
-- the common case for unbatched, unlocated stock. This expression index normalizes NULLs
-- to a fixed sentinel so Postgres actually detects the conflict; the second concurrent
-- INSERT now fails with a real unique-violation instead of silently duplicating the
-- on-hand balance. InventoryService.recordMovement() catches that violation and retries
-- the find-then-increment path once, so the caller sees a correct merged balance, not an
-- error.
--
-- NOTE FOR FUTURE MAINTAINERS: this index cannot be expressed in prisma/schema.prisma --
-- Prisma's schema DSL does not support expression/functional indexes as of Prisma 5.x.
-- It is intentionally hand-authored SQL living only in this migration file. Always use
-- `prisma migrate dev --create-only` (and review the generated SQL before applying) for
-- any future schema change, rather than an interactive `prisma migrate dev`, so this
-- index is never silently dropped by Prisma mistaking it for an unmanaged/unwanted
-- database object during drift detection.
CREATE UNIQUE INDEX "stock_identity_key_idx" ON "stock" (
  "warehouseId",
  COALESCE("locationId", ''),
  COALESCE("productId", ''),
  COALESCE("materialId", ''),
  COALESCE("batchNumber", '')
);
